apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-docker-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "java-docker-chart.name" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort }}
